
# Disable triggering from code updates to repo
trigger: none

# Set up build pipeline to trigger release on completion
resources:
  pipelines:
  - pipeline: 'reddynaresh76.sample'
    source: 'reddynaresh76.sample'
    trigger:
      branches:
      - main
      
  - pipeline: 'reddynaresh76.test-flux'
    source: 'reddynaresh76.test-flux'
    trigger:
      branches:
      - main

stages:
- stage: 'deploy_stuff'
  pool:
    name: Default
  jobs: 
  - job: deploy_stuff
    steps:
    - checkout: none # Don't check out any git repos
   
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'specific'
        project: 'naresherlaplli'
        definition: $(Build.DefinitionName)
        preferTriggeringPipeline: true
        artifactName: drop
        downloadPath: '$(System.ArtifactsDirectory)/$(Build.BuildNumber)/'
        extractTars: false

    - task: OneLuckiDev.json2variable.vsts-json-to-variable.oneLuckiDevJson2Variable@1
      displayName: 'JSON to Variable'
      inputs:
        jsonFile: '$(System.ArtifactsDirectory)/$(Build.BuildNumber)/drop/pipeline.json'
        variablePrefix: '$(Build.DefinitionName)'

  
    - script: |
      kubectl set image deployment/nginx-deployment nginx=reddynaresh76/testrepo:$(Build.BuildNumber) 