# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: checkout
    displayName: PullRepo
    steps:
      - script: 
         git clone https://reddynaresh76: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@github.com/reddynaresh76/sample.git /home/ubuntu/git/sample1
  - job: Build
    dependsOn: checkout
    condition: succeeded()
    displayName: Build
    steps:
    - script: 
       whoami
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '/home/ubuntu/git/sample1/Dockerfile'
        repository: reddynaresh76/testrepo
        tags: |
          nareshe2
    - task: Docker@2
      displayName: Push Container Image
      inputs:
        command: 'push'
        repository: reddynaresh76/testrepo
        tags: nareshe2
